project:
  type: website

website:
  title: "TrifunctionalProteomicsDataViewer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Shiny App"
        href: shiny.qmd
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



